### ISSUE TITLE
Lincensing?

### ISSUE THREAD

**Issue by ariel-codes** [transkatgirl/TheMoodMeter#1]
Firstly, I just wanna say thanks! I actually use the extended mood meter pretty regularly, and it's become a thing among some friends too 😅

But now I wanna build a mobile app, syncing/backup/notifying, version of it (open source and free of course). But **there's no license on the repo**, so could you add one (or give your written blessing here)? No worries if not, _it's your work after all_.

**Comment by transkatgirl** [comment]
Oh sure, I've added a license to the repository now.
